### ISSUE TITLE
Undefined_method 'exists'

### ISSUE THREAD

**Issue by tadartefactorist** [jpmcgrath/shortener#162] opened 2023-04-21 16:02 UTC
Hi,

On Rails 7 & ruby 3.2.2 i receive the following errors when using the shortened link:

> NoMethodError in Shortener::ShortenedUrlsController#show
> undefined method `exists?' for File:Class

```
def preferred_path
   lookup_paths.find { \|path\| File.exists? path }
end
```

the trace:
voight_kampff (1.1.4) lib/voight_kampff/test.rb:36:in `block in preferred_path'
voight_kampff (1.1.4) lib/voight_kampff/test.rb:36:in `each'
voight_kampff (1.1.4) lib/voight_kampff/test.rb:36:in `find'
voight_kampff (1.1.4) lib/voight_kampff/test.rb:36:in `preferred_path'
[voight_kampff (1.1.4) lib/voight_kampff/test.rb:57:in `crawlers'](http://localhost:5000/s/_08t0m#)

**Comment by fschwahn** [comment] 2023-04-21 16:49
A new version needs to be released - you can run off head.

Closing as duplicate of #161

**Closed by fschwahn** 2023-04-21 16:49 UTC
