### ISSUE TITLE
"unique_key" violates not-null constraint

### ISSUE THREAD

**Issue by thesubr00t** [jpmcgrath/shortener#74] opened 2016-09-25 17:50 UTC
Using Rails 5.0.0.1 with PostgreSQL, when I try to generate a shortened_url I get:

`PG::NotNullViolation: ERROR:  null value in column "unique_key" violates not-null constraint`

I tried to debug the custom create action defined in [app/models/shortener/shortened_url.rb#L125](https://github.com/jpmcgrath/shortener/blob/develop/app/models/shortener/shortened_url.rb#L125), but it seems that it was never called.

Does the create method name changed in Rails 5?

**Comment by ealdent** [comment] 2016-10-03 18:09
I dug into this briefly and it looks like the correct method name is being found, it's just not calling it.  When I call the `create_record` method directly it still doesn't call the overridden version.  Also it forces the owner to be present because the default validation for polymorphic associations is for them to be present in Rails 5, it would seem.

**Comment by craigmcnamara** [comment] 2018-04-26 06:55
There is a fix for this problem in https://github.com/jpmcgrath/shortener/pull/95. 

The issue is the key generation uses an exception to on creation to check if the unique_key is a duplicate.

I used a technique I saw in http://railscasts.com/episodes/352-securing-an-api to neatly check in a loop until a unique key is confirmed by the DB, then attempting to save the record once.

The gist of it is here: https://github.com/craigmcnamara/shortener/blob/master/app/models/shortener/shortened_url.rb#L125-L130

**Closed** 2018-05-25 05:33 UTC
